name: "CONFIG COLLECTOR"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Execute PHP script
        run: |
          php collector.php
          git config --global user.email "h.dastangoo@gmail.com"
          git config --global user.name "HadiDastangoo"
          git config credential.helper store
          git add -A
          git commit -m "✔ Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
